### ISSUE TITLE
Currently loaded data should persist across activity recreation

### ISSUE THREAD

**Issue by rtzoeller** [welnanick/Issue-Manager-for-Github#12]
The loaded data appears to be dropped on activity death/recreation, so another network call is made to reload the data. This increases data usage and latency on rotation and resizing.

Instead, the currently loaded data should be cached and displayed without making another network request.

You can recreate this by loading an issue, turning on airplane mode, and rotating the device. The activity created on rotation will never display any information.

**Comment by welnanick** [comment]
Completely forgot about that, thanks.
