### ISSUE TITLE
Pinned repositories aren't appearing in the left drawer when on the activity showing the list of pinned repositories

### ISSUE THREAD

**Issue by rtzoeller** [welnanick/Issue-Manager-for-Github#18]
I can see them when I am in other activities.

**Comment by rtzoeller** [comment]
It actually looks like this is more complicated. If I change which repos I have pinned, then press back, the drawers on previous activities won't have changed.

**Comment by welnanick** [comment]
The left drawer and the pinned repositories are not connected.

**Comment by welnanick** [comment]
The left drawer only shows the repositories that have pinned issues connected to them. So I can pin issues in "JakeWharton/butterknife" and "welnanick/Issue-Manager-for-Github" and those two repositories will be the one's displayed in the left drawer regardless of what repositories I have pinned.

Similarly, if I have no issues pinned, but have the repositories "JakeWharton/butterknife" and "welnanick/Issue-Manager-for-Github" pinned, they will show up on the main page under Pinned Repositories, but not in the left drawer.

**Comment by rtzoeller** [comment]
https://drive.google.com/file/d/11rPQEKEHNdr6iffbo66E-DVrSabqyvL0/view

General tomfoolery is afoot.

**Comment by rtzoeller** [comment]
I understand that. Let me try to get a better clip of the behavior.

**Comment by rtzoeller** [comment]
![jun 27 2018 3_08 pm](https://user-images.githubusercontent.com/573497/41997569-f5e72350-7a1d-11e8-8e3a-0a3981162d9a.gif)

**Comment by rtzoeller** [comment]
From a state with no apps pinned:

1. Select a repo
2. Select an issue
3. Pin the issue
4. Open the drawer to confirm the issue has appeared in it
5. Close the drawer
6. Press back
7. Open the drawer and notice the issue has not appeared

**Comment by welnanick** [comment]
I noticed some other weird behavior. I might not be refreshing the pinned repos properly.

**Comment by welnanick** [comment]
Should be fixed in 583d2e5
